name: HubSpot CMS Deploy
author: HubSpot
description: Publish website files to your HubSpot CMS account
branding:
  icon: "upload-cloud"
  color: "orange"
inputs:
  src_dir:
    description: Directory in project to be published
    required: true
  dest_dir:
    description: Directory in account which project will be published to
    require: true
  portal_id:
    description: Target HubSpot account (Should be stored in secrets)
    required: true
  personal_access_key:
    description: HubSpot personal access key (Should be stored in secrets)
    required: true
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: Deploy
      env:
        HUBSPOT_PORTAL_ID: ${{ inputs.portal_id }}
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key }}
      run: |
        npx --yes --package=@hubspot/cli@latest --call='hs upload ${{ inputs.src_dir }} ${{ inputs.dest_dir }} --use-env'
      shell: bash
